# Generated by Django 2.2.14 on 2020-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='Unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.CharField(default='Unknown', max_length=10, null=True),
        ),
    ]
