# Generated by Django 2.2.14 on 2020-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201030_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='rating_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
