# Generated by Django 2.2.14 on 2020-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201101_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(default='Unknown', max_length=5, null=True)),
                ('birthplace', models.CharField(default='Unknown', max_length=30, null=True)),
                ('birthday', models.CharField(default='Unknown', max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
