# Generated by Django 2.2.14 on 2020-11-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_peopleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleitem',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10, null=True),
        ),
    ]
