# Generated by Django 2.2.14 on 2020-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_followitem_followlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePeopleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_slug', models.CharField(max_length=100)),
                ('people_slug', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
