# Generated by Django 2.2.14 on 2020-11-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_moviepeoplerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleitem',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
